### PR TITLE
Feature/controller actions session types

### PR DESCRIPTION
**Pull request by ppatriotis**
Basically gets rid of all of the

`_rest*METHOD*Collection()`

methods and replaces them with base methods on vanilla controllers that are just:

`*METHOD*()`

### CODE REVIEW

**Comment by conord33** [comment]
It looks good to me.  I don't really see what the point of renaming everything is though.  Is it just to make it more readable?

**Comment by ppatriotis** [comment]
Because we added base paths for regular controllers. The old methods were basically just implementations of endpoints that function on the base path. This way, there's one mechanism for base methods. I think @maxmamis can probably explain as well.

**Comment by conord33** [comment]
So we are gonna have to update all of the Collection methods in the controllers of the projects right?

**Comment by ppatriotis** [comment]
Yes. I already have the changes in queue for FT once we get this through. They aren't huge changes, just renames.

**Comment by conord33** [comment]
Excellent

**Comment by maxmamis** [comment]
Did you make the changes for both the mobile admin APIs?

**Comment by ppatriotis** [comment]
Yes

**Pull request merged**
